language: python
branches:
  only:
  - master
install:
- pip install pelican
- pip install ghp-import
script:
- make publish github
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    secure: Ppl1JHWNIvJSeewdATofwnYJgV3rCqVRjpfCsZG85qgeOuLz4tG3ANSUd+6WIFCwanW/sog5DYpNlAZ4Sb1eyHVK0O1Uv7KnacppvYccLfwYcsiXp+hfMxodAwiDwzICDemfb0DOYERzezvu5yuPmPB2jS9SPtnvN74/pZYHY3E=
